### ISSUE TITLE
Can`t build app

### ISSUE THREAD

**Issue by 8fa94** [RadhiFadlillah/qamel#15] opened 2019-08-06 11:19 UTC
Hallo .
```
qamel build -o output/desktop-app.exe --copy-deps
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating syso file...icon file doesn't exist
Generating code for QML objects...done
Building app...
Failed to build app : exit status 1
go build github.com/RadhiFadlillah/qamel: E:\Go\pkg\tool\windows_amd64\cgo.exe:  exit status 2
```
How can i solve this problem?
Thanks.

**Comment by RadhiFadlillah** [comment] 2019-08-07 11:16
Hi @8fa94, could you give me the output for `go env` and `qamel profile print` please.

**Comment by 8fa94** [comment] 2019-08-08 03:18
Hi,  @RadhiFadlillah 
This problem was solved, but brings new problem.
output:
```
C:\Users\root\go\src\hallo_world>qamel build -o output/desktop-app.exe --copy-deps
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating syso file...icon file doesn't exist
Generating code for QML objects...done
Building app...
Failed to build app: exit status 2
# github.com/RadhiFadlillah/qamel
application.cpp:2:10: fatal error: QApplication: No such file or directory
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.


C:\Users\root\go\src\hallo_world>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\root\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\root\go
set GOPROXY=
set GORACE=
set GOROOT=E:\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\root\AppData\Local\Temp\go-build293066310=/tmp/go-build -gno-record-gcc-switches

C:\Users\root\go\src\hallo_world>qamel profile print
Details of profile default
OS      : windows
Arch    : amd64
Static  : false
Qmake   : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\qmake.exe
Moc     : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\moc.exe
Rcc     : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\rcc.exe
Gcc     : gcc.exe
G++     : g++.exe
Objdump : objdump.exe
Windres : E:\qt\qt5.13.0\Tools\mingw730_64\bin\windres.exe
```

**Comment by RadhiFadlillah** [comment] 2019-08-10 05:28
Hi @8fa94, sorry for late response.

I reckon you are using Qt from [official installer](https://www.qt.io/download-qt-installer), correct? If so, It seems you are using the wrong `gcc`, `g++` and `objdump`. You should use the one that provided by `mingw`, so your profile should look like this :

```
Details of profile default
OS      : windows
Arch    : amd64
Static  : false
Qmake   : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\qmake.exe
Moc     : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\moc.exe
Rcc     : E:\qt\qt5.13.0\5.13.0\mingw73_64\bin\rcc.exe
Gcc     : E:\qt\qt5.13.0\Tools\mingw730_64\bin\gcc.exe
G++     : E:\qt\qt5.13.0\Tools\mingw730_64\bin\g++.exe
Objdump : E:\qt\qt5.13.0\Tools\mingw730_64\bin\objdump.exe
Windres : E:\qt\qt5.13.0\Tools\mingw730_64\bin\windres.exe
```

**Comment by 8fa94** [comment] 2019-08-11 03:25
Hi, @RadhiFadlillah Thank you for your patient help.
I tried following your installation wiki,and same profiles as you ,but he said gcc is not in my %PATH% ,and appear the frist problem,and then I tried add `E:\qt\qt5.13.0\Tools\mingw730_64\bin` to environment  PATH ,the frist problem was solved,but there is a second problem,
```Failed to build app: exit status 2
# github.com/RadhiFadlillah/qamel
application.cpp:2:10: fatal error: QApplication: No such file or directory
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.
```
profile is the same as you,but has the same wrong.

**Comment by RadhiFadlillah** [comment] 2019-08-11 15:25
@8fa94 that's a bit weird. I can't reproduce it even on a freshly installed Windows 7.

> but he said gcc is not in my %PATH%

Normally, even if `gcc` is not set in your environment variable, `qamel` should be still able to build because `qamel` will [register](https://github.com/RadhiFadlillah/qamel/blob/master/internal/generator/cgo.go#L103) the temporary environment variable automatically.

With that said, if you don't mind, could you give me more information :

- Could you update `qamel` again and give me the output for `qamel --version` ? BTW, for updating `qamel`, you might need to delete the old files in directory `%GOPATH%/src/github.com/RadhiFadlillah/qamel`.
- I forgot to ask what is your OS ? Is it Windows 7 or Windows 10 ?
- Which shells that you use ? Is it the normal `cmd`, `powershell`, or third party shell like `cmder` ?

Thanks !

**Comment by 8fa94** [comment] 2019-08-14 11:08
@RadhiFadlillah I try in new  environment  OS:Windows 10
and just install QT and GO and i try again. Use cmd.
```
C:\Users\root\go\src\github.com\RadhiFadlillah\qamel\examples\hello-world>qamel build -o output/desktop-app.exe --copy-deps
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...done
Generating Qt resource file...done
Generating syso file...icon file doesn't exist
Generating code for QML objects...done
Building app...
Failed to build app: exit status 1
go build runtime/cgo: c:\go\pkg\tool\windows_amd64\cgo.exe: exit status 2

C:\Users\root\go\src\github.com\RadhiFadlillah\qamel\examples\hello-world>qamel --version
qamel version 715de5446c83d5543369f3a88891f4e170cc0d2a

C:\Users\root\go\src\github.com\RadhiFadlillah\qamel\examples\hello-world>qamel profile print
Details of profile default
OS      : windows
Arch    : amd64
Static  : false
Qmake   : C:\Qt\Qt5.13.0\5.13.0\mingw73_64\bin\qmake.exe
Moc     : C:\Qt\Qt5.13.0\5.13.0\mingw73_64\bin\moc.exe
Rcc     : C:\Qt\Qt5.13.0\5.13.0\mingw73_64\bin\rcc.exe
Gcc     : C:\Qt\Qt5.13.0\Tools\mingw730_64\bin\gcc.exe
G++     : C:\Qt\Qt5.13.0\Tools\mingw730_64\bin\g++.exe
Objdump : C:\Qt\Qt5.13.0\Tools\mingw730_64\bin\objdump.exe
Windres : C:\Qt\Qt5.13.0\Tools\mingw730_64\bin\windres.exe

```
Thanks!

**Comment by RadhiFadlillah** [comment] 2019-08-21 09:15
Hi @8fa94, sorry for late response.

I've tested it in a freshly installed Windows 10, and I can confirm this issue happened when using `cmd` and `powershell`. However, the qamel works properly when I'm using [`cmder`](https://cmder.net/).

Unfortunately, after several days I still haven't found the cause which make qamel works in `cmder` but not in other terminal. So, for now, as far as I tested, `cmder` is the only terminal in Windows that compatible with qamel.

With that said, if you don't mind, could you test it out using `cmder` ? Even the `cmder-mini` should works fine.

Thanks !

**Comment by 8fa94** [comment] 2019-09-08 12:16
@RadhiFadlillah Thank you for your patience.
I solved the problem after i used cmder.

**Comment by RadhiFadlillah** [comment] 2019-09-08 14:00
Hi @8fa94, glad it worked out for you.

I'll close this issue for now. For the problem with `cmd` and `powershell`, it will be tracked in #18.

**Closed as completed by RadhiFadlillah** 2019-09-08 14:00 UTC
